### ISSUE TITLE
Problems with 'npm start' and missing template

### ISSUE THREAD

**Issue by xiroV** [briot/geneapro#21]
Hi,
This project looks super interesting, so I wanted to try it out.
However, I'm having trouble installing the JS libraries with npm (that's what I'm guessing 'npm start' does), and starting the server with `npm run server` gives a `TemplateDoesNotExist` exception.

**What I did**
I cloned the repository, made sure I had the required packages installed, ran `npm start`.

**System:** Arch Linux 64-bit using Firefox
(Since the repositories of Arch Linux is mostly bleeding-edge/rolling release, `python` is Python3 per default. I took this into account, however I changed the first line of geneaprove.py to

```
#!/usr/bin/env python2
```

**Output of `npm start`:**
```
> geneaprove@0.1.0 start /home/xirov/geneapro
> npm install && npm run webpack && ./geneaprove.py

npm WARN optional SKIPPING OPTIONAL DEPENDENCY: fsevents@^1.0.0 (node_modules/chokidar/node_modules/fsevents):
npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.0.17: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
npm WARN @angular/core@2.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/core@2.4.7 requires a peer of zone.js@^0.7.2 but none was installed.
npm WARN @angular/http@2.4.7 requires a peer of rxjs@^5.0.1 but none was installed.
npm WARN @angular/router@3.4.7 requires a peer of rxjs@^5.0.1 but none was installed.

> geneaprove@0.1.0 webpack /home/xirov/geneapro
> webpack -d --colors

Hash: 607106db77d8a16b9701
Version: webpack 1.13.3
Time: 8989ms
                             Asset       Size  Chunks             Chunk Names
          fontawesome-webfont.woff      98 kB          [emitted]  
  glyphicons-halflings-regular.eot    20.1 kB          [emitted]  
 glyphicons-halflings-regular.woff    23.4 kB          [emitted]  
  glyphicons-halflings-regular.ttf    45.4 kB          [emitted]  
  glyphicons-halflings-regular.svg     109 kB          [emitted]  
           fontawesome-webfont.eot     166 kB          [emitted]  
         fontawesome-webfont.woff2    77.2 kB          [emitted]  
glyphicons-halflings-regular.woff2      18 kB          [emitted]  
           fontawesome-webfont.ttf     166 kB          [emitted]  
           fontawesome-webfont.svg     444 kB          [emitted]  
              geneaprove.bundle.js     332 kB       0  [emitted]  geneaprove
                  vendor.bundle.js    4.04 MB       1  [emitted]  vendor
                    geneaprove.map     445 kB       0  [emitted]  geneaprove
                        vendor.map    4.79 MB       1  [emitted]  vendor
                        index.html  569 bytes          [emitted]  
    + 490 hidden modules

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:41:21 
Property 'behavior' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:42:15 
Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 type argument(s).

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:56:26 
Module '"/home/xirov/geneapro/node_modules/@types/d3/index"' has no exported member 'ZoomEvent'.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:186:15 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:212:14 
Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 type argument(s).

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:220:21 
Parameter 'gen' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:245:17 
Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 type argument(s).

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:261:14 
Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 type argument(s).

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:270:15 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:274:19 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:278:18 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:288:18 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:292:19 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/d3.service.ts:318:14 
Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 type argument(s).

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:354:21 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:355:21 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:356:19 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:357:22 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:358:22 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:361:30 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:362:21 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:363:19 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:364:22 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:365:22 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:399:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:412:21 
Generic type 'Selection<GElement, Datum, PElement, PDatum>' requires 4 type argument(s).

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:423:29 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:530:27 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:582:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/fanchart.ts:588:15 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:352:25 
Module '"/home/xirov/geneapro/node_modules/@types/d3/index"' has no exported member 'selection'.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:410:34 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:439:34 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:459:21 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:469:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:476:28 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:480:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:481:25 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:542:25 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:543:25 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:544:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:548:23 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:552:20 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:552:23 
Parameter 'i' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:553:26 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:553:29 
Parameter 'i' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:555:15 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:557:27 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:557:30 
Parameter 'i' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:559:27 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:559:30 
Parameter 'i' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:565:37 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:570:17 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:576:28 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:577:18 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/pedigree.ts:578:18 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.service.ts:81:15 
Module '"/home/xirov/geneapro/node_modules/@types/d3/index"' has no exported member 'scale'.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.service.ts:91:23 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:66:29 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:66:41 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:70:25 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:70:37 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:71:26 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:71:38 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:75:15 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:98:15 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:133:18 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:133:30 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:134:18 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:134:30 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:135:22 
Parameter 'personList' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:135:34 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:152:29 
Parameter 'f' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/quilts.ts:152:32 
Parameter 'layer' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/radial.ts:67:22 
Property 'layout' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/radial.ts:100:27 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:12:15 
Module '"/home/xirov/geneapro/node_modules/@types/d3/index"' has no exported member 'scale'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:15:23 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:36:19 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:40:19 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:46:19 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:49:19 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:76:18 
Argument of type '{ fill: (d: any) => any; title: (d: any) => any; x: (d: any) => any; width: (d: any) => number; y...' is not assignable to parameter of type 'string'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:77:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:78:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:79:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:80:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.generations.ts:81:24 
Parameter 'd' implicitly has an 'any' type.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:12:15 
Module '"/home/xirov/geneapro/node_modules/@types/d3/index"' has no exported member 'scale'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:15:23 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:37:37 
Module '"/home/xirov/geneapro/node_modules/@types/d3/index"' has no exported member 'layout'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:55:41 
Property 'layout' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:59:19 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:62:19 
Property 'scale' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:71:19 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:74:19 
Property 'svg' does not exist on type 'typeof "/home/xirov/geneapro/node_modules/@types/d3/index"'.

ERROR in [default] /home/xirov/geneapro/resources/ts/stats.lifespan.ts:113:15 
Argument of type '{ title: (d: ILifeSpan) => string; x: (d: ILifeSpan) => any; y: (d: ILifeSpan) => number; height:...' is not assignable to parameter of type 'string'.
Child html-webpack-plugin for "index.html":
        + 1 hidden modules
Performing system checks...

System check identified no issues (0 silenced).
[utils 2017-02-16 20:49:47,475] DEBUG (0.000) 
            SELECT name, type FROM sqlite_master
            WHERE type in ('table', 'view') AND NOT name='sqlite_sequence'
            ORDER BY name; args=None
[utils 2017-02-16 20:49:47,503] DEBUG (0.000) SELECT "django_migrations"."app", "django_migrations"."name" FROM "django_migrations"; args=()
February 16, 2017 - 20:49:47
Django version 1.10.3, using settings 'mysites.settings'
Starting development server at http://127.0.0.1:8000/
Quit the server with CONTROL-C.
Internal Server Error: /favicon.ico
Traceback (most recent call last):
  File "/usr/lib/python2.7/site-packages/django/core/handlers/exception.py", line 39, in inner
    response = get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 249, in _legacy_get_response
    response = self._get_response(request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/usr/lib/python2.7/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/home/xirov/geneapro/geneaprove/urls.py", line 37, in static
    return index(request)
  File "/home/xirov/geneapro/geneaprove/urls.py", line 28, in index
    return render_to_response('index.html', c)
  File "/usr/lib/python2.7/site-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/usr/lib/python2.7/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
TemplateDoesNotExist: index.html
[16/Feb/2017 20:50:03] "GET /favicon.ico HTTP/1.1" 500 107800
```

Hope I didn't skip through any important part which lead to this, otherwise my apologies. Also I hope that someone can help me get this working.

I've been interested in Genealogy for years, however I haven't found a tool that I really enjoy to use yet. I actually stumpled upon this repo, because I was considering developing something myself.

Cheers!

**Comment by briot** [comment]
Hello, I am only now seeing your open issue on github, sorry about that ! I was in the middle of very significant changes (moving from Angular2 to React), so it might be worth retrying now. I have also reviewed the initial setup, and it was confirmed as working by someone else.
Thanks to create-react-app, starting the server will now automatically open the web page at the right address. In your example above, you were connecting directly to the server port (:8000), when in fact you need to connect to the client's port (:3000). That would explain the exception you were seeing.
The software if very rough around the edges, but all reports help clean things up, so thanks for doing one !
