### ISSUE TITLE
Import Gedcom fails after file selection with 403 Forbidden.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#29]
Attempting to import a `.ged` file fails. There seems to be a problem exchanging the csrf token.

(On the upside, the error is correctly reported with the proposed fixes to `src/Server/Import.tsx` changing:
```
error: 'Upload failed with error {resp.status}, {resp.statusText}',
```
to:
```
error: `Upload failed with error ${resp.status}, ${resp.statusText}`,
```
Previously, the browser error message was:
```
Upload failed with {resp.status}, {resp.statusText}
```
instead of:
```
Upload failed with error 403, Forbidden
```
)

See logs for error below here:

browser message on import:
```
Geneaprove could not import your file

This is either because your file does not contain correct GEDCOM data, or more likely because of limitations in Geneaprove. Please report this issue to the geneaprove developers on github. If your GEDCOM data contains information you wish to keep private, you can use the gedcom_anon.py script to anonymize the data before you send it.

Upload failed with error 403, Forbidden
```

geneaprove.log:
```
2018-04-19 22:26:03,450 send_csrf Sending csrf
```

geneaprove_django.log:
```
2018-04-19 22:26:03,459 log_message "GET /data/csrf HTTP/1.1" 200 127
2018-04-19 22:26:04,417 handle_uncaught_exception Internal Server Error: /invalid
Traceback (most recent call last):
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/python_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/backend/geneaprove/urls.py", line 57, in static
    return index(request)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/backend/geneaprove/urls.py", line 36, in index
    return render_to_response('index.html', c)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/python_env/lib/python3.6/site-packages/django/shortcuts.py", line 21, in render_to_response
    content = loader.render_to_string(template_name, context, using=using)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/python_env/lib/python3.6/site-packages/django/template/loader.py", line 67, in render_to_string
    template = get_template(template_name, using=using)
  File "/Users/clarson/Desktop/python_playground/geneapro.compare/python_env/lib/python3.6/site-packages/django/template/loader.py", line 25, in get_template
    raise TemplateDoesNotExist(template_name, chain=chain)
django.template.exceptions.TemplateDoesNotExist: index.html
2018-04-19 22:26:04,567 log_message "GET /invalid HTTP/1.1" 500 87361
2018-04-19 22:29:01,000 _reject Forbidden (CSRF token missing or incorrect.): /data/import
2018-04-19 22:29:01,004 log_message "POST /data/import HTTP/1.1" 403 2502
```

**Comment by briot** [comment]
> Upload failed with error 403, Forbidden
> 2018-04-19 22:26:03,450 send_csrf Sending csrf

I was trying to reproduce that issue (and fixed a number of issues with the import page,
for me it wasn’t even accessible because a new version of react-router seems to have
changed things significantly).

But I see no problem with csrf on my side, and was able to successfully import the page.

The way things are supposed to work is:

 * public/index.html is downloaded from Django. It contains a <script> tag that loads
   “/data/csrf” from the server. From the log you sent, I think this is where the error is:

> 2018-04-19 22:26:03,459 log_message "GET /data/csrf HTTP/1.1" 200 127
> 2018-04-19 22:26:04,417 handle_uncaught_exception Internal Server Error: /invalid

  On my side, the response from the server is a mostly empty page, but that contains
  a ‘set-cookie’ header.

* afterwards, javascript will send the csrf cookie along with queries, if it can find it.


Could you double-check what was sent by ‘/data/csrf’, using the inspector in your
browser. It seems to me that URL wasn’t correctly handled

Thanks
Emmanuel

**Comment by changeling** [comment]
The csrf issue seems to have been fixed by your changes. Running into new import issues, and I'll open a new `Issue` for those. This issue seems ready to close.
