### ISSUE TITLE
Import of stress test file TGC55C fails with 'log_message "POST /data/import HTTP/1.1" 500 59'.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#33]
Importing this file fails as noted in subject. The same occurs, with the same patterns in the log attached, with my own gedcom files.

See attached logs.

[TGC55C_import_geneaprove.log](https://github.com/briot/geneapro/files/1934836/TGC55C_import_geneaprove.log)

[TGC55C_import_geneaprove_django.log](https://github.com/briot/geneapro/files/1934837/TGC55C_import_geneaprove_django.log)

**Comment by briot** [comment]
> Importing this file fails as noted in subject. The same occurs, with the same patterns in the log attached, with my own gedcom files.

I can reproduce the error.
I am in fact in the process of rewriting the importer to use simpler data structures and be
more efficient. Should take me a few more days at least...

**Comment by changeling** [comment]
Wow, that was quick! I'll test right away.

**Comment by changeling** [comment]
Strange. The two commits you merged from my PRs (`Update src/Dashboard.tsx file and public/assets directory. ` and `Added `.vsgitbuild` and `backend/geneaprove.log` to `.gitignore`.` seem to be gone from your master, though they still show up under your closed Pull Requests as having been merged.

Any thoughts? Did this happen due to a rebase? Should I resubmit the pull requests?

**Comment by changeling** [comment]
OK. So I ran a test on a fresh master downloaded as a `.zip` from your master branch, and repeated the test using git to fetch your master branch. I then tried once more clearing browser cookies. In all three scenarios, after running `./setup.sh`, when the browser launches, I get:

```
/Users/clarson/Desktop/python_playground/geneapro.new.working/src/Server/Person.tsx
(20,4): Type '{ id: number; name: string; birthISODate: string | undefined; deathISODate: string | undefined; m...' is not assignable to type 'Person'.
  Types of property 'style' are incompatible.
    Type '{ fill: RGBColor | HSLColor | null | undefined; stroke: RGBColor | HSLColor | null | undefined; c...' is not assignable to type 'PersonStyle | undefined'.
      Type '{ fill: RGBColor | HSLColor | null | undefined; stroke: RGBColor | HSLColor | null | undefined; c...' is not assignable to type 'PersonStyle'.
        Types of property 'fill' are incompatible.
          Type 'RGBColor | HSLColor | null | undefined' is not assignable to type 'ColorCommonInstance | undefined'.
            Type 'null' is not assignable to type 'ColorCommonInstance | undefined'.
```

**Comment by briot** [comment]
Your patches disappeared because of a bad manipulation on my part, very sorry about that. I have reapplied them and pushed the changes again ! I'll pay more attention next time...

I tried also from scratch, and do not see the same error. It is kind of worrisome that the typescript/node toolchain doesn't systematically report all error messages... I guess the difference might come from a difference version of the @types/d3-color package (1.0.5 for me). But that's an issue if we can't get the exact same two versions installed on different setups.

I did a tentative blind patch

**Comment by changeling** [comment]
No worries! I need practice rebasing in git anyway. ::grin::

Your patch seems to have fixed the color issue. I have little experience with javascript, and had tried to find a fix, but just didn't understand the syntax enough. This was a good lesson in how to js. I had bypassed this temprarily by just directly defining the style for Person in the jsonPersonToPerson function. Now I know how to allow null.

I'm now running into another error, but this one is python, where I'm very comfortable. :)

Here's the error:

```
Traceback (most recent call last):
File "/Users/clarson/Desktop/geneapro.temp/geneapro-master/backend/geneaprove/importers/gedcomimport.py", line 1689, in parse
m = GedcomImporter(filename)
File "/Users/clarson/Desktop/geneapro.temp/geneapro-master/backend/geneaprove/importers/gedcomimport.py", line 71, in __init__
self._process_FILE(filename)
File "/Users/clarson/Desktop/geneapro.temp/geneapro-master/backend/geneaprove/importers/gedcomimport.py", line 75, in _process_FILE
self._data = parse_gedcom(filename)
File "/Users/clarson/Desktop/geneapro.temp/geneapro-master/backend/geneaprove/utils/gedcom.py", line 865, in parse_gedcom
result = FILE.parse(_Lexical(_File(filename)))
File "/Users/clarson/Desktop/geneapro.temp/geneapro-master/backend/geneaprove/utils/gedcom.py", line 38, in __init__
f = open(filename, "rb")
TypeError: expected str, bytes or os.PathLike object, not InMemoryUploadedFile
```

**Comment by changeling** [comment]
Only had a brief time to play with this, so I'm tossing this in the comment instead of a git change.

It looks to me like, by this point, `filename` is already a data structure, so doesn't need to be opened. Simply assigned to `self.buffer`. Dinner party pending, so in order to remain with a happy girlfriend, I need to run. I _think_ this fixes the problem, though. Check my work?

In file `backend/geneaprove/utils/gedcom.py` class definition for `_File`:

```
class _File(object):
    def __init__(self, filename):
        self.buffer = filename.read()
        self.pos = 0
```

**Comment by briot** [comment]
> It looks to me like, by this point, filename is already a data structure, so doesn't need to be opened. Simply assigned to self.buffer. Dinner party pending, so in order to remain with a happy girlfriend, I need to run. I think this fixes the problem, though. Check my work?


Not quite correct. The importer can also be used from the command line (“manage.py import”), so it
needs to handle both cases (it used to, and then I did not port that change in the rewrite)

**Comment by changeling** [comment]
I thought that might be the case. Didn't want to offer a pull request based on a rushed review. Dinner party went well, and it looks like you did a thorough fix! Thanks!

On import, I'm getting into the file, successfully with TGC55C, but failing on my own larger file, which yields the error:

```
Line 2255 Unexpected text value after EVEN
```

on this line, with context:

```
1 EVEN Pilot Grove Cemetery, Find A Grave Memorial #148243528
2 TYPE CEMETERY
2 SOUR @S0002@
```

**Comment by briot** [comment]
> Line 2255 Unexpected text value after EVEN
> 
> on this line, with context:
> 
> 1 EVEN Pilot Grove Cemetery, Find A Grave Memorial #148243528
> 2 TYPE CEMETERY
> 2 SOUR @S0002@

Is this within a 
    0 INDI
or 
    0 FAM
record ?

According to gedcom 5.5.1 (http://phpgedview.sourceforge.net/ged551-5.pdf, p35),
“EVEN” should not have a text for an INDI, though for a FAM (p32) it does.

What software was used to generate the gedcom ?

In any case, I will make the grammar more flexible (currently it is quite strict on purpose,
to detect such inconsistencies, and make sure I am aware of the variations in gedcom
among all the software that exists).

You can apply the following patch:

diff --git a/backend/geneaprove/utils/gedcom.py b/backend/geneaprove/utils/gedcom.py
index d741ecb..cdab46f 100644
--- a/backend/geneaprove/utils/gedcom.py
+++ b/backend/geneaprove/utils/gedcom.py
@@ -665,7 +665,7 @@ INDIVIDUAL_EVENT_STRUCT = [
     F("WILL", 0, unlimited, "Y", INDI_EV_DETAIL),
     F("GRAD", 0, unlimited, "Y", INDI_EV_DETAIL),
     F("RETI", 0, unlimited, "Y", INDI_EV_DETAIL),
-    F("EVEN", 0, unlimited, "Y", INDI_EV_DETAIL),
+    F("EVEN", 0, unlimited, "", INDI_EV_DETAIL),
 ]


which I’ll incorporate cleanly once I have your replies to the questions above

**Comment by briot** [comment]
Also:
maybe you would consider using the gedcom_anon.py script (at the root of the
repository) to send me your gedcom file, so that I can test it for myself ?
It won’t anonymize everything, but I won’t publish it…

Not sure how one exchanges email addresses without them being tracked forever
in github comments, which I’d like to avoid.
