### ISSUE TITLE
During Stats generation, the following exception occurs. Seems to continue OK.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#43]
Seeing this error occur during process generated by clicking on `Stats`, though it appears to continue processing:

```
2019-02-16 01:18:56,546 exception 24931 123145453756416 Internal Server Error: /data/stats/1
Traceback (most recent call last):
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/backend/geneaprove/views/to_json.py", line 173, in get
    return self.__internal(self.get_json, params, *args, **kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/backend/geneaprove/views/to_json.py", line 158, in __internal
    resp = method(params, *args, **kwargs) or {"success": True}
  File "/Users/clarson/Desktop/geneapro-test-django-branch/backend/geneaprove/views/stats.py", line 68, in get_json
    b_year = int(p.birthISODate[0:4]) if p.birthISODate else None
ValueError: invalid literal for int() with base 10: '960-'
```

**Comment by changeling** [comment]
Just to update. The process finally died on:

```
2019-02-16 02:07:10,174 handle_uncaught_exception Internal Server Error: /data/stats/1
Traceback (most recent call last):
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/python_env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/backend/geneaprove/views/to_json.py", line 173, in get
    return self.__internal(self.get_json, params, *args, **kwargs)
  File "/Users/clarson/Desktop/geneapro-test-django-branch/backend/geneaprove/views/to_json.py", line 158, in __internal
    resp = method(params, *args, **kwargs) or {"success": True}
  File "/Users/clarson/Desktop/geneapro-test-django-branch/backend/geneaprove/views/stats.py", line 68, in get_json
    b_year = int(p.birthISODate[0:4]) if p.birthISODate else None
ValueError: invalid literal for int() with base 10: '960-'
Total time: 2857.255560s  /  queries time (428 queries): 5.776000s
2019-02-16 02:07:23,219 log_message "GET /data/stats/1?max_age=0&bar_width=2 HTTP/1.1" 500 116727
```
