### ISSUE TITLE
Migration fails on 0005_MIL_to_MILT.py after model changes.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#44]
Stacktrace:

```
Running migrations:
  Applying geneaprove.0005_MIL_to_MILT...Traceback (most recent call last):
  File "./manage.py", line 22, in <module>
    execute_from_command_line(sys.argv)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 367, in execute_from_command_line
    utility.execute()
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/management/__init__.py", line 359, in execute
    self.fetch_command(subcommand).run_from_argv(self.argv)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/management/base.py", line 294, in run_from_argv
    self.execute(*args, **cmd_options)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/management/base.py", line 345, in execute
    output = self.handle(*args, **options)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/management/commands/migrate.py", line 204, in handle
    fake_initial=fake_initial,
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 115, in migrate
    state = self._migrate_all_forwards(state, plan, full_plan, fake=fake, fake_initial=fake_initial)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 145, in _migrate_all_forwards
    state = self.apply_migration(state, migration, fake=fake, fake_initial=fake_initial)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/migrations/executor.py", line 244, in apply_migration
    state = migration.apply(state, schema_editor)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/migrations/migration.py", line 129, in apply
    operation.database_forwards(self.app_label, schema_editor, old_state, project_state)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/migrations/operations/special.py", line 189, in database_forwards
    self.code(from_state.apps, schema_editor)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/backend/geneaprove/migrations/0005_MIL_to_MILT.py", line 12, in forward
    m = EType.objects.get(gedcom='_MIL')
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/models/manager.py", line 85, in manager_method
    return getattr(self.get_queryset(), name)(*args, **kwargs)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/db/models/query.py", line 385, in get
    self.model._meta.object_name
__fake__.DoesNotExist: Event_Type matching query does not exist.

You have 2 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): geneaprove.
Run 'python manage.py migrate' to apply them.
```

**Comment by changeling** [comment]
Closing. Creating new database works without error. Migrating existing database fails.

**Comment by briot** [comment]
> Closing. Creating new database works without error. Migrating existing database fails.

That’s expected for now.
Given there’s no way to edit a database anyway, I currently take shortcuts and expect users
to recreate the database...
