### ISSUE TITLE
On fresh install, before database has been loaded with data, endless stream of stacktrack.

### ISSUE THREAD

**Issue by changeling** [briot/geneapro#45]
Fresh install.
No database created yet.
Run `setup.sh`.
When `setup.sh` is complete, browser window launched, no other actions taken.

Console fills with endless stream of:

```
2019-02-17 00:30:59,954 log_message "GET /data/pedigree/1?gens=7&descendant_gens=0&theme=undefined HTTP/1.1" 500 27
2019-02-17 00:31:00,099 get geneaprove.views.pedigree.PedigreeData.get(<JSONViewParams: {'gens': ['7'], 'descendant_gens': ['0'], 'theme': ['undefined']}>)
2019-02-17 00:31:00,099 get_json get pedigree data
2019-02-17 00:31:00,100 handle_uncaught_exception Internal Server Error: /data/pedigree/1
Traceback (most recent call last):
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/handlers/exception.py", line 42, in inner
    response = get_response(request)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 187, in _get_response
    response = self.process_exception_by_middleware(e, request)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/core/handlers/base.py", line 185, in _get_response
    response = wrapped_callback(request, *callback_args, **callback_kwargs)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/views/generic/base.py", line 68, in view
    return self.dispatch(request, *args, **kwargs)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/python_env/lib/python3.6/site-packages/django/views/generic/base.py", line 88, in dispatch
    return handler(request, *args, **kwargs)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/backend/geneaprove/views/to_json.py", line 173, in get
    return self.__internal(self.get_json, params, *args, **kwargs)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/backend/geneaprove/views/to_json.py", line 158, in __internal
    resp = method(params, *args, **kwargs) or {"success": True}
  File "/Library/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 52, in inner
    return func(*args, **kwds)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/backend/geneaprove/views/pedigree.py", line 45, in get_json
    decujus = global_graph.node_from_id(id)
  File "/Users/clarson/Desktop/ged_files/geneapro-master/backend/geneaprove/views/graph.py", line 107, in node_from_id
    return self.__nodes[id]
KeyError: 1
2019-02-17 00:31:00,101 log_message "GET /data/pedigree/1?gens=7&descendant_gens=0&theme=undefined HTTP/1.1" 500 27
```

**Comment by changeling** [comment]
I was able to get this to stop. Here are the steps I took, with, I believe, some combination of these fixing the problem:

Quit running instance.
Delete database.
Clear browser cache, including `Site Preferences` in Firefox.
Run setup.
Import small database (`test_short.ged`).
Under Pedigree, choose a theme.
Quit running instance.
Delete database.
Run `setup.sh`.

No more stacktrace.
